export const iconImages: any = {
    "Swim trunks": require("../datas/icons/Swim trunks.png"),
    "T-shirts": require("../datas/icons/T-shirt.png"),
    "Colorful shirts": require("../datas/icons/Colorful shirts.png"),
    "Shorts": require("../datas/icons/Shorts.png"),
    "Swim shorts": require("../datas/icons/Swim shorts.png"),
    "Underwear": require("../datas/icons/Underwear.png"),
    "Socks": require("../datas/icons/Socks.png"),
    "Hat": require("../datas/icons/Hat.png"),
    "Light jacket": require("../datas/icons/Light jacket.png"),
    "Sunglasses": require("../datas/icons/Sunglasses.png"),
    "Beach bag": require("../datas/icons/Beach bag.png"),
    "Water bottle": require("../datas/icons/Water bottle.png"),
    "Energy drinks": require("../datas/icons/Energy drinks.png"),
    "Sunscreen": require("../datas/icons/Sunscreen.png"),
    "Moisturizer": require("../datas/icons/Moisturizer.png"),
    "Shampoo": require("../datas/icons/Shampoo.png"),
    "Conditioner": require("../datas/icons/Conditioner.png"),
    "Toothpaste": require("../datas/icons/Toothpaste.png"),
    "Toothbrush": require("../datas/icons/Toothbrush.png"),
    "Deodorant": require("../datas/icons/Deodorant.png"),
    "Razor": require("../datas/icons/Razor.png"),
    "Shaving cream": require("../datas/icons/Shaving cream.png"),
    "Phone": require("../datas/icons/Phone.png"),
    "Charger": require("../datas/icons/Charger.png"),
    "Camera": require("../datas/icons/Camera.png"),
    "Portable charger": require("../datas/icons/Portable charger.png"),
    "First aid kit": require("../datas/icons/First aid kit.png"),
    "Pain relievers": require("../datas/icons/Pain relievers.png"),
    "Bandages": require("../datas/icons/Bandages.png"),
    "ID": require("../datas/icons/ID.png"),
    "Hotel reservation details": require("../datas/icons/Hotel reservation details.png"),
    "Flight tickets": require("../datas/icons/Flight tickets.png"),
    "Beach towel": require("../datas/icons/Beach towel.png"),
    "Waterproof phone case": require("../datas/icons/Waterproof phone case.png"),
    "Thermal base layers": require("../datas/icons/Thermal base layers.png"),
    "Fleece jacket": require("../datas/icons/Fleece jacket.png"),
    "Windbreaker": require("../datas/icons/Windbreaker.png"),
    "Hiking pants": require("../datas/icons/Hiking pants.png"),
    "Hiking shorts": require("../datas/icons/Hiking shorts.png"),
    "Thermal underwear": require("../datas/icons/Thermal underwear.png"),
    "Waterproof jacket": require("../datas/icons/Waterproof jacket.png"),
    "Raincoat": require("../datas/icons/Raincoat.png"),
    "Gloves": require("../datas/icons/Gloves.png"),
    "Glasses": require("../datas/icons/Glasses.png"),
    "Energy bars": require("../datas/icons/Energy bars.png"),
    "Nuts": require("../datas/icons/Nuts.png"),
    "Cooking set": require("../datas/icons/Cooking set.png"),
    "Camp coffee maker": require("../datas/icons/Camp coffee maker.png"),
    "Insect repellent": require("../datas/icons/Insect repellent.png"),
    "GPS device": require("../datas/icons/GPS device.png"),
    "Insect bite cream": require("../datas/icons/Insect bite cream.png"),
    "ID and passport": require("../datas/icons/ID and passport.png"),
    "Insurance documents": require("../datas/icons/Insurance documents.png"),
    "Map and compass": require("../datas/icons/Map and compass.png"),
    "Tent": require("../datas/icons/Tent.png"),
    "Sleeping bag": require("../datas/icons/Sleeping bag.png"),
    "Sleeping pad": require("../datas/icons/Sleeping pad.png"),
    "Camp stove": require("../datas/icons/Camp stove.png"),
    "Backpack": require("../datas/icons/Backpack.png"),
    "Flashlight": require("../datas/icons/Flashlight.png"),
    "Tent repair kit": require("../datas/icons/Tent repair kit.png"),
    "Shirts": require("../datas/icons/Shirts.png"),
    "Smart jackets": require("../datas/icons/Smart jackets.png"),
    "Pants": require("../datas/icons/Pants.png"),
    "Jewelry": require("../datas/icons/Jewelry.png"),
    "Snacks": require("../datas/icons/Snacks.png"),
    "Extra memory cards": require("../datas/icons/Extra memory cards.png"),
    "City map": require("../datas/icons/City map.png"),
    "Camping pants": require("../datas/icons/Camping pants.png"),
    "Ski jacket": require("../datas/icons/Ski jacket.png"),
    "Ski pants": require("../datas/icons/Ski pants.png"),
    "Thermal leggings": require("../datas/icons/Thermal leggings.png"),
    "Waterproof gloves": require("../datas/icons/Waterproof gloves.png"),
    "Ski hat": require("../datas/icons/Ski hat.png"),
    "Ski goggles": require("../datas/icons/Ski goggles.png"),
    "Neck gaiter": require("../datas/icons/Neck gaiter.png"),
    "Ski socks": require("../datas/icons/Ski socks.png"),
    "Hot drinks": require("../datas/icons/Hot drinks.png"),
    "Ski poles": require("../datas/icons/Ski poles.png"),
    "Helmet": require("../datas/icons/Helmet.png"),
    "Ski boots": require("../datas/icons/Ski boots.png"),
    "Swimwear": require("../datas/icons/Swimwear.png"),
    "Tank tops": require("../datas/icons/Tank tops.png"),
    "Rash guard": require("../datas/icons/Rash guard.png"),
    "Beach pants": require("../datas/icons/Beach pants.png"),
    "Rain poncho": require("../datas/icons/Rain poncho.png"),
    "After-sun lotion": require("../datas/icons/After-sun lotion.png"),
    "Hairbrush": require("../datas/icons/Hairbrush.png"),
    "Wet wipes": require("../datas/icons/Wet wipes.png"),
    "Aftershave": require("../datas/icons/Aftershave.png"),
    "Antiseptic wipes": require("../datas/icons/Antiseptic wipes.png"),
    "Snow boots": require("../datas/icons/Snow boots.png"),
    "Ski bag": require("../datas/icons/Ski bag.png"),
    "Ski gloves": require("../datas/icons/Ski gloves.png"),
    "Thermos": require("../datas/icons/Thermos.png"),
    "Lip balm": require("../datas/icons/Lip balm.png"),
    "Thermal blanket": require("../datas/icons/Thermal blanket.png"),
}